### ISSUE TITLE
k4dirstat 3.2.0-1build1 - crashes on Kubuntu 20.04 when clicking "Open"

### ISSUE THREAD

**Issue by vlrmt** [jeromerobert/k4dirstat#34]
Hi,
just installed, k4dirstat crashes systematically when clicking the "Open" button (Segmentation fault).

Stack:
```
Application: k4dirstat (k4dirstat), signal: Segmentation fault
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[Current thread is 1 (Thread 0x7fca8f21d800 (LWP 6376))]

Thread 8 (Thread 0x7fca7a168700 (LWP 6383)):
#0  futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x5573d3524268) at ../sysdeps/nptl/futex-internal.h:183
#1  __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x5573d3524218, cond=0x5573d3524240) at pthread_cond_wait.c:508
#2  __pthread_cond_wait (cond=0x5573d3524240, mutex=0x5573d3524218) at pthread_cond_wait.c:638
#3  0x00007fca8511f62b in ?? () from /usr/lib/x86_64-linux-gnu/dri/r600_dri.so
#4  0x00007fca8511f23b in ?? () from /usr/lib/x86_64-linux-gnu/dri/r600_dri.so
#5  0x00007fca91c0f609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#6  0x00007fca9242a103 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 7 (Thread 0x7fca7a969700 (LWP 6382)):
#0  futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x5573d3524268) at ../sysdeps/nptl/futex-internal.h:183
#1  __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x5573d3524218, cond=0x5573d3524240) at pthread_cond_wait.c:508
#2  __pthread_cond_wait (cond=0x5573d3524240, mutex=0x5573d3524218) at pthread_cond_wait.c:638
#3  0x00007fca8511f62b in ?? () from /usr/lib/x86_64-linux-gnu/dri/r600_dri.so
#4  0x00007fca8511f23b in ?? () from /usr/lib/x86_64-linux-gnu/dri/r600_dri.so
#5  0x00007fca91c0f609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#6  0x00007fca9242a103 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 6 (Thread 0x7fca7b16a700 (LWP 6381)):
#0  futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x5573d3524268) at ../sysdeps/nptl/futex-internal.h:183
#1  __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x5573d3524218, cond=0x5573d3524240) at pthread_cond_wait.c:508
#2  __pthread_cond_wait (cond=0x5573d3524240, mutex=0x5573d3524218) at pthread_cond_wait.c:638
#3  0x00007fca8511f62b in ?? () from /usr/lib/x86_64-linux-gnu/dri/r600_dri.so
#4  0x00007fca8511f23b in ?? () from /usr/lib/x86_64-linux-gnu/dri/r600_dri.so
#5  0x00007fca91c0f609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#6  0x00007fca9242a103 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 5 (Thread 0x7fca7b96b700 (LWP 6380)):
#0  futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x5573d3524268) at ../sysdeps/nptl/futex-internal.h:183
#1  __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x5573d3524218, cond=0x5573d3524240) at pthread_cond_wait.c:508
#2  __pthread_cond_wait (cond=0x5573d3524240, mutex=0x5573d3524218) at pthread_cond_wait.c:638
#3  0x00007fca8511f62b in ?? () from /usr/lib/x86_64-linux-gnu/dri/r600_dri.so
#4  0x00007fca8511f23b in ?? () from /usr/lib/x86_64-linux-gnu/dri/r600_dri.so
#5  0x00007fca91c0f609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#6  0x00007fca9242a103 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 4 (Thread 0x7fca84b91700 (LWP 6379)):
#0  futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x5573d36fbb88) at ../sysdeps/nptl/futex-internal.h:183
#1  __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x5573d36fbb38, cond=0x5573d36fbb60) at pthread_cond_wait.c:508
#2  __pthread_cond_wait (cond=0x5573d36fbb60, mutex=0x5573d36fbb38) at pthread_cond_wait.c:638
#3  0x00007fca8511f62b in ?? () from /usr/lib/x86_64-linux-gnu/dri/r600_dri.so
#4  0x00007fca8511f23b in ?? () from /usr/lib/x86_64-linux-gnu/dri/r600_dri.so
#5  0x00007fca91c0f609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#6  0x00007fca9242a103 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 3 (Thread 0x7fca8c86e700 (LWP 6378)):
#0  0x00007fca913c512e in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#1  0x00007fca913c6aff in g_main_context_check () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007fca913c7152 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007fca913c72e3 in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007fca92b08583 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x00007fca92aaf4db in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#6  0x00007fca928e7785 in QThread::exec() () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#7  0x00007fca91e8defa in ?? () from /lib/x86_64-linux-gnu/libQt5DBus.so.5
#8  0x00007fca928e89d2 in ?? () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#9  0x00007fca91c0f609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#10 0x00007fca9242a103 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 2 (Thread 0x7fca8e0ef700 (LWP 6377)):
#0  0x00007fca9241d96f in __GI___poll (fds=0x7fca8e0eeca8, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007fca91217c1a in ?? () from /lib/x86_64-linux-gnu/libxcb.so.1
#2  0x00007fca9121990a in xcb_wait_for_event () from /lib/x86_64-linux-gnu/libxcb.so.1
#3  0x00007fca8e8f3298 in ?? () from /lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#4  0x00007fca928e89d2 in ?? () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x00007fca91c0f609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#6  0x00007fca9242a103 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 1 (Thread 0x7fca8f21d800 (LWP 6376)):
[KCrash Handler]
#6  0x00007fca9323c368 in QStandardItem::rowCount() const () from /lib/x86_64-linux-gnu/libQt5Gui.so.5
#7  0x00007fca93240c74 in QStandardItem::setRowCount(int) () from /lib/x86_64-linux-gnu/libQt5Gui.so.5
#8  0x00007fca93241113 in ?? () from /lib/x86_64-linux-gnu/libQt5Gui.so.5
#9  0x00007fca93241c59 in QStandardItemModel::itemFromIndex(QModelIndex const&) const () from /lib/x86_64-linux-gnu/libQt5Gui.so.5
#10 0x00005573d1e380fb in KDirSortFilterProxyModel::lessThan(QModelIndex const&, QModelIndex const&) const ()
#11 0x00007fca92a90462 in ?? () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#12 0x00007fca92a9294f in ?? () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#13 0x00007fca92a9344a in ?? () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#14 0x00007fca92a95900 in ?? () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#15 0x00007fca92a85f95 in ?? () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#16 0x00007fca92a8aa7f in ?? () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#17 0x00007fca92a8e0f6 in ?? () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#18 0x00007fca92a8ed03 in ?? () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#19 0x00007fca92adc300 in QMetaObject::activate(QObject*, int, int, void**) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#20 0x00007fca92a5cca2 in QAbstractItemModel::rowsInserted(QModelIndex const&, int, int, QAbstractItemModel::QPrivateSignal) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#21 0x00007fca92a65768 in QAbstractItemModel::endInsertRows() () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#22 0x00007fca940b34d8 in ?? () from /lib/x86_64-linux-gnu/libKF5KIOWidgets.so.5
#23 0x00007fca92adc458 in QMetaObject::activate(QObject*, int, int, void**) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#24 0x00007fca93ebc00e in KCoreDirLister::itemsAdded(QUrl const&, KFileItemList const&) () from /lib/x86_64-linux-gnu/libKF5KIOCore.so.5
#25 0x00007fca93ebe9b3 in ?? () from /lib/x86_64-linux-gnu/libKF5KIOCore.so.5
#26 0x00007fca93ed0638 in ?? () from /lib/x86_64-linux-gnu/libKF5KIOCore.so.5
#27 0x00007fca92adc458 in QMetaObject::activate(QObject*, int, int, void**) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#28 0x00007fca93e67e88 in KIO::ListJob::entries(KIO::Job*, QList<KIO::UDSEntry> const&) () from /lib/x86_64-linux-gnu/libKF5KIOCore.so.5
#29 0x00007fca93e69822 in ?? () from /lib/x86_64-linux-gnu/libKF5KIOCore.so.5
#30 0x00007fca92adc458 in QMetaObject::activate(QObject*, int, int, void**) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#31 0x00007fca93e407c9 in KIO::SlaveInterface::listEntries(QList<KIO::UDSEntry> const&) () from /lib/x86_64-linux-gnu/libKF5KIOCore.so.5
#32 0x00007fca93e431b6 in KIO::SlaveInterface::dispatch(int, QByteArray const&) () from /lib/x86_64-linux-gnu/libKF5KIOCore.so.5
#33 0x00007fca93e40f4f in KIO::SlaveInterface::dispatch() () from /lib/x86_64-linux-gnu/libKF5KIOCore.so.5
#34 0x00007fca93e4a152 in KIO::Slave::gotInput() () from /lib/x86_64-linux-gnu/libKF5KIOCore.so.5
#35 0x00007fca92adc458 in QMetaObject::activate(QObject*, int, int, void**) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#36 0x00007fca92adcd5a in QObject::event(QEvent*) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#37 0x00007fca934c8a66 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#38 0x00007fca934d20f0 in QApplication::notify(QObject*, QEvent*) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#39 0x00007fca92ab093a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#40 0x00007fca92ab35b8 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#41 0x00007fca92b08f67 in ?? () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#42 0x00007fca913c6fbd in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#43 0x00007fca913c7240 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#44 0x00007fca913c72e3 in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#45 0x00007fca92b08565 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#46 0x00007fca92aaf4db in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#47 0x00007fca936ccc6d in QDialog::exec() () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#48 0x00007fca936ccb71 in QDialog::exec() () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#49 0x00007fca936e0aba in QFileDialog::getExistingDirectoryUrl(QWidget*, QString const&, QUrl const&, QFlags<QFileDialog::Option>, QStringList const&) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#50 0x00005573d1e276fc in k4dirstat::fileAskOpenDir() ()
#51 0x00007fca92adc300 in QMetaObject::activate(QObject*, int, int, void**) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#52 0x00007fca934c23e6 in QAction::triggered(bool) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#53 0x00007fca934c4aa2 in QAction::activate(QAction::ActionEvent) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#54 0x00007fca935bee10 in ?? () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#55 0x00007fca935bf035 in QAbstractButton::mouseReleaseEvent(QMouseEvent*) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#56 0x00007fca936b25fe in QToolButton::mouseReleaseEvent(QMouseEvent*) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#57 0x00007fca9350b2b6 in QWidget::event(QEvent*) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#58 0x00007fca936b26a8 in QToolButton::event(QEvent*) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#59 0x00007fca934c8a66 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#60 0x00007fca934d2343 in QApplication::notify(QObject*, QEvent*) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#61 0x00007fca92ab093a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#62 0x00007fca934d1457 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#63 0x00007fca9352735d in ?? () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#64 0x00007fca9352a1ec in ?? () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#65 0x00007fca934c8a66 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#66 0x00007fca934d20f0 in QApplication::notify(QObject*, QEvent*) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#67 0x00007fca92ab093a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#68 0x00007fca92e997d3 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () from /lib/x86_64-linux-gnu/libQt5Gui.so.5
#69 0x00007fca92e9b10b in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () from /lib/x86_64-linux-gnu/libQt5Gui.so.5
#70 0x00007fca92e7535b in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /lib/x86_64-linux-gnu/libQt5Gui.so.5
#71 0x00007fca8e8f432e in ?? () from /lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#72 0x00007fca913c6fbd in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#73 0x00007fca913c7240 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#74 0x00007fca913c72e3 in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#75 0x00007fca92b08565 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#76 0x00007fca92aaf4db in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#77 0x00007fca92ab7246 in QCoreApplication::exec() () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#78 0x00005573d1e1f9a6 in main ()
[Inferior 1 (process 6376) detached]
```

**Comment by jeromerobert** [comment]
Duplicate #28 #32 #33

**Comment by vlrmt** [comment]
> Duplicate #28 #32 #33

Oops... I didn't see those in the list of open issues. Thanks for the information!
So I'll have to wait for release 3.2.1 to get released for [K]Ubuntu 20.04.

**Comment by jeromerobert** [comment]
I fear it's not that simple. 20.04 is a LTS and I don't think it will receive a fix for k4dirstat (it's not critical enough). k4dirstat is already fixed in 20.10 which will be released end of october. If needed I can add it to my PPA.

**Comment by vlrmt** [comment]
Well, in terms of application usability, this is a critical issue unfortunately. But as you said, from a distribution point of view, it's much less critical...
I know more or less nothing about Ubuntu's applications updates policy, so I can just trust your experience about it. Being offered an alternative way to use version 3.2.1 would be great of course, so I would surely not refuse your proposal :) I'm used to K4DirStat and would love to stick to it as much has possible.

**Comment by vlrmt** [comment]
I've just downloaded and manually installed this binary package:
https://launchpad.net/ubuntu/groovy/amd64/k4dirstat/3.2.1-1
Works great :)

As a side note (but this isn't linked to release 3.2.1), after disk analysis has completed, pressing F9 does not hide the graphical "chart" as it should. Apparently, this is just a question of GUI focus at this moment. Clicking anywhere in the folders tree section, then pressing F9 again, works as expected.

**Comment by jeromerobert** [comment]
Thanks, it's good to know that the Groovy package work on 20.04 ! It means that KDE did not change enough between 20.04 and 20.10 to break ABI. It also mean that, at least for now, I don't need to upload 3.2.1 on my PPA.

I'll have a look to that focus problem.

**Comment by vlrmt** [comment]
Deal :) I'm fine with a standalone package, even if it won't get upgraded automatically. I'll keep an eye on a possible future Ubuntu releases though, in case release 3.2.1 gets pushed to end users one day.
Thanks for what you can do about this F9 issue as well :) I'd also love to be able to _disable_ it (meaning no need to press F9 each time), since I'm not taking advantage of this graphical feature. From what I remember, I couldn't find a way to disable it once and for all.
Other than that, I love your software, so useful! Thanks a lot for your work Jérôme (provided this is your first name).

**Comment by jeromerobert** [comment]
> I'd also love to be able to disable it (meaning no need to press F9 each time)

This #30. Fixed but not yet released.
