### ISSUE TITLE
Crash on click on column name

### ISSUE THREAD

**Issue by tenzap** [jeromerobert/k4dirstat#41]
On Debian bullseye, K4DirStat 3.2.2

Open K4dir stat, select a folder
Click on the 'Last change" column, then on the "name" column.
At that time, the app will crash

For most folders it does crash (for few folders, always the same, it doesn't crash)

```
Application: k4dirstat (k4dirstat), signal: Aborted

[KCrash Handler]
#4  0x00007fbf3247fce1 in raise () from /lib/x86_64-linux-gnu/libc.so.6
#5  0x00007fbf32469537 in abort () from /lib/x86_64-linux-gnu/libc.so.6
#6  0x00007fbf3246940f in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#7  0x00007fbf32478662 in __assert_fail () from /lib/x86_64-linux-gnu/libc.so.6
#8  0x00005601a4c6c4f1 in KDirStat::KDirSortFilterProxyModel::lessThan(QModelIndex const&, QModelIndex const&) const ()
#9  0x00007fbf32ba1467 in ?? () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#10 0x00007fbf32ba4973 in ?? () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#11 0x00007fbf32b95cff in ?? () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#12 0x00007fbf32b9a393 in ?? () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#13 0x00007fbf32bfe5e0 in ?? () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#14 0x00007fbf338efc5f in QHeaderView::sortIndicatorChanged(int, Qt::SortOrder) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#15 0x00007fbf338f87cc in QHeaderView::mouseReleaseEvent(QMouseEvent*) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#16 0x00007fbf336c9fae in QWidget::event(QEvent*) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#17 0x00007fbf3377242e in QFrame::event(QEvent*) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#18 0x00007fbf32bc7d33 in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#19 0x00007fbf3368a14e in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#20 0x00007fbf3369104b in QApplication::notify(QObject*, QEvent*) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#21 0x00007fbf32bc7fca in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#22 0x00007fbf33690076 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#23 0x00007fbf336e2011 in ?? () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#24 0x00007fbf336e533e in ?? () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#25 0x00007fbf3368a15f in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#26 0x00007fbf32bc7fca in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#27 0x00007fbf32fa2583 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () from /lib/x86_64-linux-gnu/libQt5Gui.so.5
#28 0x00007fbf32f7864c in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /lib/x86_64-linux-gnu/libQt5Gui.so.5
#29 0x00007fbf2e6937da in ?? () from /lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#30 0x00007fbf314f2e6b in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#31 0x00007fbf314f3118 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#32 0x00007fbf314f31cf in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#33 0x00007fbf32c1f51f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#34 0x00007fbf32bc698b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#35 0x00007fbf32bcec00 in QCoreApplication::exec() () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#36 0x00005601a4c58802 in main ()
[Inferior 1 (process 1005949) detached]
```

**Comment by tenzap** [comment]
Simply clicking on the header of column name also leads to as crash (no need to click the "last change" column before)

**Comment by tenzap** [comment]
thanks for the fix
