### ISSUE TITLE
Crash when opening files-subtree of directory with only one empty file

### ISSUE THREAD

**Issue by belgoking** [jeromerobert/k4dirstat#44]
Application: k4dirstat (3.3.0)

Qt Version: 5.15.2
Frameworks Version: 5.85.0
Operating System: Linux 5.10.0-8-amd64 x86_64
Windowing System: X11
Drkonqi Version: 5.21.5
Distribution: Debian GNU/Linux bookworm/sid

-- Information about the crash:
I have a directory containing one subdirectory and exactly one empty File (`.NOBACKUP`). When I open that directory in _k4dirstat_ and then open the virtual `<Files>`-node, _k4dirstat_ reliably crashes with the stack trace I have appended.

The crash can be reproduced every time.

-- Backtrace:
`Application: k4dirstat (k4dirstat), signal: Floating point exception`

[KCrash Handler]
```
#4  0x000055a097bd9587 in ?? ()
#5  0x00007f455b8c1c88 in QTreeView::drawRow(QPainter*, QStyleOptionViewItem const&, QModelIndex const&) const () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#6  0x00007f455b8c5896 in QTreeView::drawTree(QPainter*, QRegion const&) const () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#7  0x00007f455b8c5b6e in QTreeViewPrivate::renderTreeToPixmapForAnimation(QRect const&) const () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#8  0x00007f455b8c9410 in QTreeViewPrivate::beginAnimatedOperation() () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#9  0x00007f455b8c9647 in QTreeViewPrivate::expand(int, bool) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#10 0x00007f455b8caea6 in QTreeViewPrivate::expandOrCollapseItemAtPos(QPoint const&) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#11 0x00007f455b8cd68d in QTreeView::mousePressEvent(QMouseEvent*) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#12 0x00007f455b63efae in QWidget::event(QEvent*) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#13 0x00007f455b6e72fe in QFrame::event(QEvent*) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#14 0x00007f455ab3cd33 in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#15 0x00007f455b5ff14e in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#16 0x00007f455b60604b in QApplication::notify(QObject*, QEvent*) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#17 0x00007f455ab3cfca in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#18 0x00007f455b605076 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#19 0x00007f455b657011 in ?? () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#20 0x00007f455b65a33e in ?? () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#21 0x00007f455b5ff15f in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#22 0x00007f455ab3cfca in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#23 0x00007f455af17583 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () from /lib/x86_64-linux-gnu/libQt5Gui.so.5
#24 0x00007f455aeed64c in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /lib/x86_64-linux-gnu/libQt5Gui.so.5
#25 0x00007f45561077da in ?? () from /lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#26 0x00007f455930085b in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#27 0x00007f4559300b08 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#28 0x00007f4559300bbf in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#29 0x00007f455ab9451f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#30 0x00007f455ab3b98b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#31 0x00007f455ab43c00 in QCoreApplication::exec() () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#32 0x000055a097bbe97a in ?? ()
#33 0x00007f455a39ee4a in __libc_start_main (main=0x55a097bbe3a0, argc=2, argv=0x7ffc051b2b88, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffc051b2b78) at ../csu/libc-start.c:314
#34 0x000055a097bbeb2a in ?? ()
[Inferior 1 (process 514945) detached]
```

**Comment by jeromerobert** [comment]
Thank you !
